version: '3.9'
services:
  user_backend:
    build: .
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    depends_on:
      - user_db
    env_file:
      - .env

  user_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"